# Generated by Django 3.2 on 2022-05-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppAgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('min_age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AppKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=3000)),
                ('download_counter', models.PositiveBigIntegerField(default=0)),
                ('last_update', models.DateField(auto_now=True)),
                ('age_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appagelimit')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appkind')),
            ],
        ),
    ]
