# Generated by Django 3.2 on 2022-05-25 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='download_counter',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='last_update',
            field=models.DateField(default=datetime.date(2022, 5, 25)),
        ),
    ]
