# Generated by Django 3.2 on 2022-05-25 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220525_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2022, 5, 25, 19, 28, 39, 564363, tzinfo=utc)),
        ),
    ]
